-- ─────────────────────────────────────────────────────────────────────────────
-- FR-023: Voice-to-Text  |  FR-024: Auto SOAP  |  FR-025: AI Risk Scoring
-- Tables: voice_sessions, risk_assessments, clinical_tasks
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── 1. Voice Sessions Table (FR-023) ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.voice_sessions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id  UUID NOT NULL UNIQUE REFERENCES public.appointments(id) ON DELETE CASCADE,
  doctor_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  audio_url       TEXT,                               -- Path or URL to encrypted audio
  transcript_raw  JSONB NOT NULL DEFAULT '[]'::jsonb,  -- Array of {speaker, text, start_time, end_time}
  transcript_edited JSONB,                            -- Edited text array
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.voice_sessions IS
  'Audio files and streaming transcription details for medical consultations (FR-023).';

-- ─── 2. Risk Assessments Table (FR-025) ──────────────────────────────────────
CREATE TYPE public.risk_level_type AS ENUM ('LOW', 'MODERATE', 'HIGH');

CREATE TABLE IF NOT EXISTS public.risk_assessments (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  exam_id         UUID NOT NULL REFERENCES public.medical_examinations(id) ON DELETE CASCADE,
  appointment_id  UUID NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  patient_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  risk_score      INTEGER NOT NULL CHECK (risk_score >= 0 AND risk_score <= 100),
  risk_level      public.risk_level_type NOT NULL,
  risk_factors    JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of {factor: string, contribution_pct: number}
  recommendation  TEXT,
  model_version   TEXT NOT NULL DEFAULT 'xgboost-v1',
  override_applied BOOLEAN NOT NULL DEFAULT FALSE,
  calculated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.risk_assessments IS
  'AI-evaluated patient risk calculations and contributing factors (FR-025).';

-- ─── 3. Clinical Tasks Table (FR-025 / Follow-up Tasks) ──────────────────────
CREATE TYPE public.clinical_task_status AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');

CREATE TABLE IF NOT EXISTS public.clinical_tasks (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id  UUID REFERENCES public.appointments(id) ON DELETE CASCADE,
  patient_id      UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  assigned_role   TEXT NOT NULL DEFAULT 'staff',      -- 'staff' (nurse), 'doctor', etc.
  title           TEXT NOT NULL,
  description     TEXT,
  status          public.clinical_task_status NOT NULL DEFAULT 'PENDING',
  due_date        DATE NOT NULL,
  override_reason TEXT,                               -- Required if cancelled by doctor
  created_by      TEXT NOT NULL DEFAULT 'system',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.clinical_tasks IS
  'Clinical follow-up tasks generated by AI or manually assigned (FR-025).';

-- ─── 4. Indexes ──────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS voice_sessions_appt_idx ON public.voice_sessions (appointment_id);
CREATE INDEX IF NOT EXISTS risk_assessments_appt_idx ON public.risk_assessments (appointment_id);
CREATE INDEX IF NOT EXISTS risk_assessments_exam_idx ON public.risk_assessments (exam_id);
CREATE INDEX IF NOT EXISTS clinical_tasks_patient_idx ON public.clinical_tasks (patient_id, status);
CREATE INDEX IF NOT EXISTS clinical_tasks_due_idx ON public.clinical_tasks (due_date);

-- ─── 5. Updated At Triggers ──────────────────────────────────────────────────
CREATE TRIGGER voice_sessions_set_updated_at
  BEFORE UPDATE ON public.voice_sessions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER clinical_tasks_set_updated_at
  BEFORE UPDATE ON public.clinical_tasks
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─── 6. RLS Policies ─────────────────────────────────────────────────────────
ALTER TABLE public.voice_sessions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risk_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinical_tasks   ENABLE ROW LEVEL SECURITY;

-- voice_sessions policies
CREATE POLICY "voice_sessions_doctor_all" ON public.voice_sessions
  FOR ALL USING (doctor_id = auth.uid()) WITH CHECK (doctor_id = auth.uid());

CREATE POLICY "voice_sessions_admin_all" ON public.voice_sessions
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND role = 'admin')
  );

-- risk_assessments policies
CREATE POLICY "risk_assessments_read_all" ON public.risk_assessments
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND role IN ('doctor', 'staff', 'admin'))
    OR patient_id = auth.uid()
  );

CREATE POLICY "risk_assessments_write_all" ON public.risk_assessments
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND role IN ('doctor', 'admin'))
  );

-- clinical_tasks policies
CREATE POLICY "clinical_tasks_select_all" ON public.clinical_tasks
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND role IN ('doctor', 'staff', 'admin'))
  );

CREATE POLICY "clinical_tasks_write_all" ON public.clinical_tasks
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND role IN ('doctor', 'staff', 'admin'))
  );

-- ─── 7. Risk Engine Trigger and Functions ────────────────────────────────────

-- Function: calculate and store risk score
CREATE OR REPLACE FUNCTION public.calculate_risk_score(p_exam_id UUID)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_exam            RECORD;
  v_appt            RECORD;
  v_patient         RECORD;
  v_vitals          RECORD;
  v_preconsult      RECORD;
  v_age             INTEGER := 30;
  v_score           INTEGER := 0;
  v_level           public.risk_level_type := 'LOW';
  v_factors         JSONB := '[]'::jsonb;
  v_recommendation  TEXT := 'Theo dõi sức khỏe thường quy và tái khám định kỳ.';
  v_icd_severity    INTEGER := 0;
  v_has_critical_icd BOOLEAN := FALSE;
  v_override        BOOLEAN := FALSE;
  v_assess_id       UUID;
BEGIN
  -- 1. Load basic examination & appointment information
  SELECT * INTO v_exam FROM public.medical_examinations WHERE id = p_exam_id;
  IF NOT FOUND THEN RETURN NULL; END IF;

  SELECT * INTO v_appt FROM public.appointments WHERE id = v_exam.appointment_id;
  SELECT * INTO v_patient FROM public.patient WHERE id_number IS NOT NULL AND user_id = v_exam.patient_id LIMIT 1;
  IF v_patient IS NULL THEN
    SELECT * INTO v_patient FROM public.patient WHERE user_id = v_exam.patient_id LIMIT 1;
  END IF;

  -- 2. Calculate Age factor (10% weight)
  IF v_patient.date_of_birth IS NOT NULL THEN
    v_age := extract(year from age(v_patient.date_of_birth));
    IF v_age >= 65 OR v_age <= 5 THEN
      v_score := v_score + 10;
      v_factors := v_factors || jsonb_build_object('factor', 'Độ tuổi nhạy cảm (Tuổi: ' || v_age || ')', 'contribution_pct', 10);
    END IF;
  END IF;

  -- 3. Load pre-consultation health history (25% weight)
  SELECT * INTO v_preconsult FROM public.pre_consultations WHERE appointment_id = v_exam.appointment_id LIMIT 1;
  IF v_preconsult.medical_history IS NOT NULL AND jsonb_array_length(v_preconsult.medical_history) > 0 THEN
    v_score := v_score + LEAST(jsonb_array_length(v_preconsult.medical_history) * 10, 25);
    v_factors := v_factors || jsonb_build_object(
      'factor', 'Bệnh sử mãn tính (' || jsonb_array_length(v_preconsult.medical_history) || ' bệnh)',
      'contribution_pct', LEAST(jsonb_array_length(v_preconsult.medical_history) * 10, 25)
    );
  END IF;

  -- 4. Load most recent vital signs (30% weight)
  SELECT * INTO v_vitals FROM public.vital_signs WHERE appointment_id = v_exam.appointment_id ORDER BY recorded_at DESC LIMIT 1;
  IF v_vitals IS NOT NULL THEN
    -- Check for Critical Overrides (RULE-025g)
    IF (v_vitals.systolic IS NOT NULL AND v_vitals.systolic > 200) OR
       (v_vitals.heart_rate IS NOT NULL AND (v_vitals.heart_rate < 40 OR v_vitals.heart_rate > 150)) THEN
      v_override := TRUE;
      v_score := 100;
      v_level := 'HIGH';
      v_factors := '[]'::jsonb || jsonb_build_object(
        'factor', 'Vượt ngưỡng sinh hiệu khẩn cấp (HA: ' || COALESCE(v_vitals.systolic::text, '--') || ', HR: ' || COALESCE(v_vitals.heart_rate::text, '--') || ')',
        'contribution_pct', 100
      );
      v_recommendation := 'Cảnh báo sinh hiệu nghiêm trọng! Ưu tiên chăm sóc khẩn cấp và tái khám trong vòng 24-48 giờ.';
    ELSE
      -- Standard scoring deviations
      DECLARE
        v_vitals_score INTEGER := 0;
      BEGIN
        IF v_vitals.systolic IS NOT NULL AND (v_vitals.systolic > 140 OR v_vitals.systolic < 90) THEN
          v_vitals_score := v_vitals_score + 15;
        END IF;
        IF v_vitals.temperature IS NOT NULL AND (v_vitals.temperature > 38.5 OR v_vitals.temperature < 35.5) THEN
          v_vitals_score := v_vitals_score + 15;
        END IF;
        IF v_vitals_score > 0 THEN
          v_score := v_score + v_vitals_score;
          v_factors := v_factors || jsonb_build_object('factor', 'Chỉ số sinh hiệu bất thường', 'contribution_pct', v_vitals_score);
        END IF;
      END;
    END IF;
  END IF;

  -- 5. Calculate Diagnoses / ICD-10 codes (25% weight)
  IF NOT v_override THEN
    DECLARE
      v_icd RECORD;
    BEGIN
      FOR v_icd IN
        SELECT icd_code FROM public.soap_icd_codes
         WHERE exam_id = p_exam_id AND confirm_status = 'CONFIRMED'
      LOOP
        -- Myocardial infarction (I21), stroke (I63), critical cardiac failure
        IF v_icd.icd_code LIKE 'I21%' OR v_icd.icd_code LIKE 'I63%' OR v_icd.icd_code LIKE 'I50%' THEN
          v_has_critical_icd := TRUE;
        END IF;
      END LOOP;

      IF v_has_critical_icd THEN
        v_score := v_score + 25;
        v_factors := v_factors || jsonb_build_object('factor', 'Chẩn đoán lâm sàng mức độ nặng (Nguy cơ tim mạch/đột quỵ)', 'contribution_pct', 25);
      ELSE
        -- Default confirmed ICD weight
        SELECT count(*) INTO v_icd_severity FROM public.soap_icd_codes WHERE exam_id = p_exam_id AND confirm_status = 'CONFIRMED';
        IF v_icd_severity > 0 THEN
          v_score := v_score + LEAST(v_icd_severity * 10, 15);
          v_factors := v_factors || jsonb_build_object('factor', 'Chẩn đoán bệnh lý được xác nhận', 'contribution_pct', LEAST(v_icd_severity * 10, 15));
        END IF;
      END IF;
    END;
  END IF;

  -- 6. Medication complexity (10% weight)
  IF NOT v_override AND v_preconsult.current_medications IS NOT NULL THEN
    IF jsonb_array_length(v_preconsult.current_medications) >= 5 THEN
      v_score := v_score + 10;
      v_factors := v_factors || jsonb_build_object('factor', 'Đa trị liệu (Sử dụng từ 5 loại thuốc trở lên)', 'contribution_pct', 10);
    END IF;
  END IF;

  -- 7. Determine level
  IF NOT v_override THEN
    -- Clamp score
    v_score := LEAST(v_score, 100);
    IF v_score >= 70 THEN
      v_level := 'HIGH';
      v_recommendation := 'Mức độ rủi ro CAO. Đề xuất tái khám và theo dõi sát sao trong vòng 7 ngày tới.';
    ELSIF v_score >= 40 THEN
      v_level := 'MODERATE';
      v_recommendation := 'Mức độ rủi ro TRUNG BÌNH. Đề xuất tái khám kiểm tra sau 2-4 tuần.';
    ELSE
      v_level := 'LOW';
      v_recommendation := 'Mức độ rủi ro THẤP. Tiếp tục theo dõi sức khỏe thường quy.';
    END IF;
  END IF;

  -- 8. Upsert Risk Assessment
  INSERT INTO public.risk_assessments (
    exam_id, appointment_id, patient_id, risk_score, risk_level, risk_factors, recommendation, override_applied
  ) VALUES (
    p_exam_id, v_exam.appointment_id, v_exam.patient_id, v_score, v_level, v_factors, v_recommendation, v_override
  )
  ON CONFLICT (exam_id) DO UPDATE SET
    risk_score = EXCLUDED.risk_score,
    risk_level = EXCLUDED.risk_level,
    risk_factors = EXCLUDED.risk_factors,
    recommendation = EXCLUDED.recommendation,
    override_applied = EXCLUDED.override_applied,
    calculated_at = now()
  RETURNING id INTO v_assess_id;

  -- 9. Trigger high risk follow-up tasks (RULE-025c)
  IF v_level = 'HIGH' THEN
    INSERT INTO public.clinical_tasks (
      appointment_id, patient_id, assigned_role, title, description, due_date
    ) VALUES (
      v_exam.appointment_id,
      v_exam.patient_id,
      'staff',
      'Theo dõi & Lên lịch tái khám 7 ngày',
      'Bệnh nhân thuộc nhóm rủi ro CAO. Cần liên hệ hỗ trợ, cập nhật sức khỏe định kỳ và lên lịch tái khám trong vòng 7 ngày.',
      (CURRENT_DATE + interval '7 days')::date
    );
  END IF;

  RETURN v_assess_id;
END;
$$;

-- Add UNIQUE constraint to risk_assessments for upsert logic
ALTER TABLE public.risk_assessments ADD CONSTRAINT risk_assessments_exam_unique UNIQUE (exam_id);

-- Trigger: Automatically calculate risk when SOAP note is signed (status -> LOCKED)
CREATE OR REPLACE FUNCTION public.after_exam_signed_calculate_risk()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF OLD.status = 'DRAFT' AND NEW.status = 'LOCKED' THEN
    PERFORM public.calculate_risk_score(NEW.id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_after_exam_signed_calculate_risk ON public.medical_examinations;
CREATE TRIGGER trg_after_exam_signed_calculate_risk
  AFTER UPDATE OF status ON public.medical_examinations
  FOR EACH ROW
  EXECUTE FUNCTION public.after_exam_signed_calculate_risk();

-- ─── 8. Realtime Enablement ──────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
     WHERE pubname = 'supabase_realtime' AND tablename = 'risk_assessments'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.risk_assessments;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
     WHERE pubname = 'supabase_realtime' AND tablename = 'clinical_tasks'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.clinical_tasks;
  END IF;
END $$;
